def generate_report(response):

    report = f"""

SEARCH HEIST AI
Executive Intelligence Report

==================================================

{response}

==================================================

Generated by Search Heist AI

"""

    return report